version: '3.8'

services:
  price-parser:
    build: .
    container_name: price-parser-bot
    volumes:
      - .:/app                         # горячая правка кода
      - ./output:/app/output           # результаты
      - ./input:/app/input             # входные файлы
      - ./temp:/app/temp               # временные файлы
      - ./logs:/app/logs               # логи
      - ./screenshots:/app/screenshots # скриншоты при ошибках

    environment:
      - TZ=Europe/Moscow
      - PYTHONUNBUFFERED=1             # Логи в реальном времени

    # Для Playwright headless Chrome
    shm_size: '2gb'
    
    # Логирование
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    # Автоматический перезапуск
    restart: unless-stopped
